from tkinter import *
def f(e):
   contd=e.get()
   print(contd)


def callback(var):
   f=entryboxes[int(str(var)[-1])]
   print(f)
   content= var.get()[0]
   if content.isalpha():
      f.delete(0, END)
      f.insert(0, content)
   else:
      f.delete(0,END)
root = Tk()
root.geometry("275x275")
root.config(bg="grey")
#user_name = Label(root,text = "                         Crossword                      ",font=20,width=10,height=2).grid(row =0,column=100) 
button = Button(root, text='    ', bg='black' ,state=DISABLED)
button.grid(row=0, column=1)
button1 = Button(root, text='    ', bg='black' ,state=DISABLED)
button1.grid(row=1, column=3)
button2 = Button(root, text='    ', bg='black' ,state=DISABLED)
button2.grid(row=2, column=3)
button3 = Button(root, text='    ', bg='black' ,state=DISABLED)
button3.grid(row=3, column=2)
button4 = Button(root, text='    ', bg='black' ,state=DISABLED)
button4.grid(row=4, column=0)
entryboxes=[]
var = StringVar()
var2=StringVar()
var3=StringVar()
var4=StringVar()
var5=StringVar()
var6=StringVar()
var7=StringVar()
var8=StringVar()
var9=StringVar()
var10=StringVar()
var11=StringVar()
var12=StringVar()
var13=StringVar()
var14=StringVar()
var15=StringVar()
var16=StringVar()
var17=StringVar()
var18=StringVar()
var19=StringVar()
var20=StringVar()
var.trace("w", lambda name, index,mode, var=var: callback(var))
var2.trace("w", lambda name, index,mode, var=var2: callback(var2))
var3.trace("w", lambda name, index,mode, var=var3: callback(var3))
var4.trace("w", lambda name, index,mode, var=var4: callback(var4))
var5.trace("w", lambda name, index,mode, var=var5: callback(var5))
var6.trace("w", lambda name, index,mode, var=var6: callback(var6))
var7.trace("w", lambda name, index,mode, var=var7: callback(var7))
var8.trace("w", lambda name, index,mode, var=var8: callback(var8))
var9.trace("w", lambda name, index,mode, var=var9: callback(var9))
var10.trace("w", lambda name, index,mode, var=var10: callback(var10))
var11.trace("w", lambda name, index,mode, var=var11: callback(var11))
var12.trace("w", lambda name, index,mode, var=var12: callback(var12))
var13.trace("w", lambda name, index,mode, var=var13: callback(var13))
var14.trace("w", lambda name, index,mode, var=var14: callback(var14))
var15.trace("w", lambda name, index,mode, var=var15: callback(var15))
var16.trace("w", lambda name, index,mode, var=var16: callback(var16))
var17.trace("w", lambda name, index,mode, var=var17: callback(var17))
var18.trace("w", lambda name, index,mode, var=var18: callback(var18))
var19.trace("w", lambda name, index,mode, var=var19: callback(var19))
var20.trace("w", lambda name, index,mode, var=var20: callback(var20))
#Create an Entry widget
e1 = Entry(root, textvariable=var,width=2,font=2,validatecommand=f(e1))
e1.grid(row=0,column=0)
entryboxes.append(e1)
e2 = Entry(root, textvariable=var2,width=2,font=2)
e2.grid(row=0,column=2)
entryboxes.append(e2)
e3 = Entry(root, textvariable=var3,width=2,font=2)
e3.grid(row=0,column=3)
entryboxes.append(e3)
e4 = Entry(root, textvariable=var4,width=2,font=2)
e4.grid(row=0,column=4)
entryboxes.append(e4)
e5 = Entry(root, textvariable=var5,width=2,font=2)
e5.grid(row=1,column=0)
entryboxes.append(e5)
e6 = Entry(root, textvariable=var6,width=2,font=2)
e6.grid(row=1,column=1)
entryboxes.append(e6)
e7 = Entry(root, textvariable=var7,width=2,font=2)
e7.grid(row=1,column=2)
entryboxes.append(e7)
e8 = Entry(root, textvariable=var8,width=2,font=2)
e8.grid(row=1,column=4)
entryboxes.append(e8)
e9 = Entry(root, textvariable=var9,width=2,font=2)
e9.grid(row=2,column=0)
entryboxes.append(e9)
e10 = Entry(root, textvariable=var10,width=2,font=2)
e10.grid(row=2,column=1)
entryboxes.append(e10)
e11 = Entry(root, textvariable=var11,width=2,font=2)
e11.grid(row=2,column=2)
entryboxes.append(e11)
e12 = Entry(root, textvariable=var12,width=2,font=2)
e12.grid(row=2,column=4)
entryboxes.append(e12)
e13 = Entry(root, textvariable=var13,width=2,font=2)
e13.grid(row=3,column=0)
entryboxes.append(e13)
e14 = Entry(root, textvariable=var14,width=2,font=2)
e14.grid(row=3,column=1)
entryboxes.append(e14)
e15 = Entry(root, textvariable=var15,width=2,font=2)
e15.grid(row=3,column=3)
entryboxes.append(e15)
e16 = Entry(root, textvariable=var16,width=2,font=2)
e16.grid(row=3,column=4)
entryboxes.append(e16)
e17 = Entry(root, textvariable=var17,width=2,font=2)
e17.grid(row=4,column=1)
entryboxes.append(e17)
e18 = Entry(root, textvariable=var18,width=2,font=2)
e18.grid(row=4,column=2)
entryboxes.append(e18)
e19 = Entry(root, textvariable=var19,width=2,font=2)
e19.grid(row=4,column=3)
entryboxes.append(e19)
e20 = Entry(root, textvariable=var20,width=2,font=2)
e20.grid(row=4,column=4)
entryboxes.append(e20)
root.mainloop()
