from tkinter import *
def callback(var):
   content= var.get()[0]
   if content.isalpha():
      e1.delete(0, END)   
      e1.insert(0, content)
   else:
      e1.delete(0,END)
root = Tk()
root.geometry("275x275")
root.config(bg="grey")
#user_name = Label(root,text = "                         Crossword                      ",font=20,width=10,height=2).grid(row =0,column=100) 
button = Button(root, text='    ', bg='black' ,state=DISABLED)
button.grid(row=0, column=1)
button1 = Button(root, text='    ', bg='black' ,state=DISABLED)
button1.grid(row=1, column=3)
button2 = Button(root, text='    ', bg='black' ,state=DISABLED)
button2.grid(row=2, column=3)
button3 = Button(root, text='    ', bg='black' ,state=DISABLED)
button3.grid(row=3, column=2)
button4 = Button(root, text='    ', bg='black' ,state=DISABLED)
button4.grid(row=4, column=0)
var = StringVar()
var.trace("w", lambda name, index,mode, var=var: callback(var))
#Create an Entry widget
e1 = Entry(root, textvariable=var,width=2,font=2)
e1.grid(row=0,column=0)
e2 = Entry(root, textvariable=var,width=2,font=2)
e2.grid(row=0,column=2)
e3 = Entry(root, textvariable=var,width=2,font=2)
e3.grid(row=0,column=3)
e4 = Entry(root, textvariable=var,width=2,font=2)
e4.grid(row=0,column=4)
e5 = Entry(root, textvariable=var,width=2,font=2)
e5.grid(row=1,column=0)
e6 = Entry(root, textvariable=var,width=2,font=2)
e6.grid(row=1,column=1)
e7 = Entry(root, textvariable=var,width=2,font=2)
e7.grid(row=1,column=2)
e8 = Entry(root, textvariable=var,width=2,font=2)
e8.grid(row=1,column=4)
e9 = Entry(root, textvariable=var,width=2,font=2)
e9.grid(row=2,column=0)
e10 = Entry(root, textvariable=var,width=2,font=2)
e10.grid(row=2,column=1)
e11 = Entry(root, textvariable=var,width=2,font=2)
e11.grid(row=2,column=2)
e12 = Entry(root, textvariable=var,width=2,font=2)
e12.grid(row=2,column=4)
e13 = Entry(root, textvariable=var,width=2,font=2)
e13.grid(row=3,column=0)
e14 = Entry(root, textvariable=var,width=2,font=2)
e14.grid(row=3,column=1)
e15 = Entry(root, textvariable=var,width=2,font=2)
e15.grid(row=3,column=3)
e16 = Entry(root, textvariable=var,width=2,font=2)
e16.grid(row=3,column=4)
e17 = Entry(root, textvariable=var,width=2,font=2)
e17.grid(row=4,column=1)
e18 = Entry(root, textvariable=var,width=2,font=2)
e18.grid(row=4,column=2)
e19 = Entry(root, textvariable=var,width=2,font=2)
e19.grid(row=4,column=3)
e20 = Entry(root, textvariable=var,width=2,font=2)
e20.grid(row=4,column=4)
root.mainloop()
